// src/views/PlatformAdmin/CouponManagement/CouponIssueRecordsPage.vue
<template>
  <sidebar>
    <div class="page-container">
      <!-- 发放记录卡片 -->
      <a-card :bordered="false" class="records-card">
        <template #title>
          <div class="header-container">
            <a-button @click="goBack" class="back-button">
              <a-icon type="arrow-left" />
              返回
            </a-button>
            <span class="title">优惠券发放记录</span>
          </div>
        </template>

        <a-table
          :columns="columns"
          :data-source="tableData"
          :loading="isLoading"
          :pagination="pagination"
          @change="handleTableChange"
          rowKey="id"
          size="middle"
        >
          <!-- 发放方式 -->
          <template slot="distributionType" slot-scope="text">
            <a-tag class="distribution-tag">
              {{ getDistributionTypeName(text) }}
            </a-tag>
          </template>

          <!-- 目标用户 -->
          <template slot="targetUsers" slot-scope="text">
            <div class="target-users">{{ text }}</div>
          </template>
        </a-table>
      </a-card>
    </div>
  </sidebar>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api'
import Sidebar from '@/components/Layout/Sidebar.vue'
import CouponService from './services/coupon.service'

export default defineComponent({
  name: 'CouponIssueRecordsPage',
  components: { Sidebar },

  data() {
    return {
      tableData: [],
      isLoading: false,
      pagination: {
        current: 1,
        pageSize: 20,
        total: 0,
        showSizeChanger: true,
        showQuickJumper: true,
        pageSizeOptions: ['10', '20', '50', '100'],
        showTotal: (total: number) => `共 ${total} 条`
      },
      columns: [
        {
          title: '优惠券',
          dataIndex: 'couponId',
          key: 'couponId',
          width: 180
        },
        {
          title: '发放方式',
          dataIndex: 'distributionType',
          key: 'distributionType',
          width: 120,
          scopedSlots: { customRender: 'distributionType' }
        },
        {
          title: '目标用户',
          dataIndex: 'targetUsers',
          key: 'targetUsers',
          scopedSlots: { customRender: 'targetUsers' }
        },
        {
          title: '发放数量',
          dataIndex: 'count',
          key: 'count',
          width: 100
        },
        {
          title: '发放时间',
          dataIndex: 'createdAt',
          key: 'createdAt',
          width: 180
        },
        {
          title: '操作人',
          dataIndex: 'createdBy',
          key: 'createdBy',
          width: 120
        }
      ]
    }
  },

  async mounted() {
    await this.loadData()
  },

  methods: {
    async loadData() {
      this.isLoading = true
      try {
        const result = await CouponService.getIssueRecords({
          page: this.pagination.current,
          pageSize: this.pagination.pageSize
        })
        this.tableData = result.data
        this.pagination.total = result.total
      } catch (error) {
        console.error('Failed to load issue records:', error)
        this.$message.error('加载发放记录失败')
      } finally {
        this.isLoading = false
      }
    },

    async handleTableChange(pagination: any) {
      this.pagination.current = pagination.current
      this.pagination.pageSize = pagination.pageSize
      await this.loadData()
    },

    goBack() {
      this.$router.push('/platform-admin/coupon-management/issue')
    },

    getDistributionTypeName(type: string): string {
      const map: Record<string, string> = {
        manual_phone: '手机号',
        manual_vip: 'VIP等级',
        auto: '自动发放'
      }
      return map[type] || type
    }
  }
})
</script>

<style scoped lang="less">
.page-container {
  padding: 24px;
  background: #f0f2f5;
  min-height: calc(100vh - 0px);

  .records-card {
    border-radius: 12px;
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
  }

  .header-container {
    display: flex;
    align-items: center;
    gap: 12px;
  }

  .back-button {
    height: 32px;
    border-color: #cbd5e1;
  }

  .title {
    font-size: 18px;
    font-weight: 600;
    color: #0f172a;
  }

  .distribution-tag {
    border-color: #cbd5e1;
  }

  .target-users {
    max-width: 200px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 14px;
    color: #0f172a;
  }
}

:deep(.ant-table-tbody > tr:hover > td) {
  background-color: #f8fafc !important;
}
</style>

// app/pages/PlatformAdmin/CouponManagement/CouponIssueRecordsPage.tsx
/**
 * 优惠券发放记录页面
 */

import { Link } from '@remix-run/react'
import type { CouponRecord } from './types/coupon.types'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'
import { Badge } from '~/components/ui/badge'
import { Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from '~/components/ui/pagination'
import { ArrowLeft } from 'lucide-react'
import MainLayout from '~/pages/PointsSystem/components/MainLayout'

interface CouponIssueRecordsPageProps {
  records: CouponRecord[]
  total: number
  page: number
  pageSize: number
  totalPages: number
  error: string | null
}

export default function CouponIssueRecordsPage({
  records,
  total,
  page,
  pageSize,
  totalPages,
  error
}: CouponIssueRecordsPageProps) {
  if (error) {
    return (
      <MainLayout>
        <div className="p-6">
          <div className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-700">
            错误: {error}
          </div>
        </div>
      </MainLayout>
    )
  }

  return (
    <MainLayout>
      <div className="p-6 space-y-6">
        <Card className="rounded-xl border-slate-200 bg-white shadow-sm">
          <CardHeader className="border-b border-slate-100">
            <div className="flex items-center gap-3">
              <Link to="/platform-admin/coupon-management/issue">
                <Button variant="outline" size="sm" className="h-8 border-slate-300">
                  <ArrowLeft className="w-4 h-4 mr-1" />
                  返回
                </Button>
              </Link>
              <CardTitle className="text-lg font-semibold text-slate-900">优惠券发放记录</CardTitle>
            </div>
          </CardHeader>
          <CardContent className="pt-6">
            <Table>
              <TableHeader>
                <TableRow className="border-slate-200 bg-slate-50">
                  <TableHead className="text-slate-900 font-semibold">优惠券</TableHead>
                  <TableHead className="text-slate-900 font-semibold">发放方式</TableHead>
                  <TableHead className="text-slate-900 font-semibold">目标用户</TableHead>
                  <TableHead className="text-slate-900 font-semibold">发放数量</TableHead>
                  <TableHead className="text-slate-900 font-semibold">发放时间</TableHead>
                  <TableHead className="text-slate-900 font-semibold">操作人</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {records.map((record) => (
                  <TableRow key={record.id} className="hover:bg-slate-50 transition-colors border-slate-200">
                    <TableCell className="text-slate-900">{record.couponId}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className="border-slate-300">
                        {record.distributionType === 'manual_phone' ? '手机号' :
                         record.distributionType === 'manual_vip' ? 'VIP等级' : '自动发放'}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-slate-900 text-sm max-w-[200px] truncate">
                      {record.targetUsers}
                    </TableCell>
                    <TableCell className="text-slate-900">{record.count || 1}</TableCell>
                    <TableCell className="text-slate-600 text-sm">{record.createdAt}</TableCell>
                    <TableCell className="text-slate-600 text-sm">{record.createdBy}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>

            {/* 统计和分页 */}
            {totalPages > 1 && (
              <div className="mt-6 flex items-center justify-between">
                <div className="text-sm text-slate-600">共 {total} 条</div>
                <Pagination>
                  <PaginationContent>
                    <PaginationItem>
                      <PaginationPrevious
                        href={page > 1 ? `?page=${page - 1}` : '#'}
                        className={page === 1 ? 'pointer-events-none opacity-50' : ''}
                      />
                    </PaginationItem>

                    {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
                      <PaginationItem key={p}>
                        <PaginationLink href={`?page=${p}`} isActive={p === page}>
                          {p}
                        </PaginationLink>
                      </PaginationItem>
                    ))}

                    <PaginationItem>
                      <PaginationNext
                        href={page < totalPages ? `?page=${page + 1}` : '#'}
                        className={page === totalPages ? 'pointer-events-none opacity-50' : ''}
                      />
                    </PaginationItem>
                  </PaginationContent>
                </Pagination>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  )
}
