// app/pages/MerchantBackend/StoreInfo/components/DisplayValue.tsx
interface DisplayValueProps {
  value: string | number | undefined | null
  emptyText?: string
  className?: string
}

export default function DisplayValue({ value, emptyText = '—', className = '' }: DisplayValueProps) {
  const displayValue = value !== undefined && value !== null && value !== '' ? String(value) : emptyText

  return (
    <div className={`min-h-[36px] flex items-center text-slate-900 ${className}`}>
      {displayValue}
    </div>
  )
}

// src/views/MerchantBackend/StoreInfo/components/DisplayValue.vue
<template>
  <div :class="`min-h-[36px] flex items-center text-slate-900 ${className}`">
    {{ displayValue }}
  </div>
</template>

<script>
import { defineComponent, computed } from '@vue/composition-api'

export default defineComponent({
  name: 'DisplayValue',
  props: {
    value: {
      type: [String, Number],
      default: undefined
    },
    emptyText: {
      type: String,
      default: '—'
    },
    className: {
      type: String,
      default: ''
    }
  },
  setup(props) {
    const displayValue = computed(() => {
      return props.value !== undefined && props.value !== null && props.value !== ''
        ? String(props.value)
        : props.emptyText
    })

    return {
      displayValue
    }
  }
})
</script>
