// src/views/PlatformAdmin/OrderManagement/OrderListPage.vue
<template>
  <sidebar>
    <div class="p-6 space-y-6">
      <!-- 订单详情弹窗 -->
      <order-detail-dialog
        :visible="isDetailDialogOpen"
        :order="selectedOrder"
        @close="isDetailDialogOpen = false"
      />

      <!-- 筛选表单 -->
      <a-card class="rounded-xl border-slate-200 bg-white shadow-sm">
        <div class="grid grid-cols-6 gap-4">
          <!-- 房型 -->
          <div class="space-y-2">
            <label class="text-sm text-slate-600">房型</label>
            <a-input
              v-model="filters.roomType"
              placeholder="请输入房型"
              class="h-9"
            />
          </div>

          <!-- 订房日期 -->
          <div class="space-y-2 col-span-2">
            <label class="text-sm text-slate-600">订房日期</label>
            <div class="flex gap-2 items-center">
              <a-date-picker
                v-model="filters.startDate"
                placeholder="开始日期"
                class="flex-1 h-9"
                format="YYYY-MM-DD"
              />
              <span>-</span>
              <a-date-picker
                v-model="filters.endDate"
                placeholder="结束日期"
                class="flex-1 h-9"
                format="YYYY-MM-DD"
              />
            </div>
          </div>

          <!-- 订单状态 -->
          <div class="space-y-2 col-span-3">
            <label class="text-sm text-slate-600">订单状态</label>
            <a-select
              v-model="filters.orderStatus"
              placeholder="全部状态"
              class="w-full"
            >
              <a-select-option value="all">全部</a-select-option>
              <a-select-option :value="OrderStatus.PENDING_PAYMENT">待支付</a-select-option>
              <a-select-option :value="OrderStatus.PENDING_CHECKIN">待入住</a-select-option>
              <a-select-option :value="OrderStatus.CHECKED_IN">入住中</a-select-option>
              <a-select-option :value="OrderStatus.CHECKED_OUT">已离店</a-select-option>
              <a-select-option :value="OrderStatus.COMPLETED">已完成</a-select-option>
              <a-select-option :value="OrderStatus.CANCELLED">已取消</a-select-option>
              <a-select-option :value="OrderStatus.REFUND_REQUESTED">退款申请</a-select-option>
            </a-select>
          </div>
        </div>

        <div class="flex gap-2 mt-4">
          <a-button type="primary" class="h-9 bg-blue-600" @click="handleSearch">
            <a-icon type="search" />
            搜索
          </a-button>
          <a-button class="h-9 border-slate-300" @click="handleReset">
            重置
          </a-button>
        </div>
      </a-card>

      <!-- 订单列表 -->
      <a-card class="rounded-xl border-slate-200 bg-white shadow-sm">
        <div slot="title" class="text-lg font-semibold text-slate-900">订单列表</div>

        <div class="border border-slate-200 rounded-lg overflow-hidden">
          <a-table
            :columns="columns"
            :data-source="orders"
            :pagination="paginationConfig"
            :loading="loading"
            row-key="id"
            @change="handleTableChange"
          >
            <!-- 订单号 -->
            <template slot="orderNumber" slot-scope="orderNumber">
              <span class="font-mono text-sm text-slate-900">{{ orderNumber }}</span>
            </template>

            <!-- 订房人 -->
            <template slot="guestInfo" slot-scope="text, record">
              <div class="space-y-1">
                <div class="font-medium text-slate-900">{{ record.guestName }}</div>
                <div class="text-sm text-slate-600">{{ record.guestPhone }}</div>
              </div>
            </template>

            <!-- 入住日期 -->
            <template slot="checkInDates" slot-scope="text, record">
              <span class="whitespace-nowrap text-slate-900">
                {{ record.checkInDate }} - {{ record.checkOutDate }}
              </span>
            </template>

            <!-- 支付金额 -->
            <template slot="actualAmount" slot-scope="actualAmount">
              <span class="text-slate-900">¥{{ actualAmount }}</span>
            </template>

            <!-- 订单状态 -->
            <template slot="status" slot-scope="status, record">
              <div class="flex items-center gap-2">
                <a-tag :class="getStatusTagClass(status)">
                  {{ ORDER_STATUS_LABELS[status] }}
                </a-tag>
                <a-badge
                  v-if="record.hasRefundRequest"
                  count="退"
                  :number-style="{ backgroundColor: '#ef4444', fontSize: '10px' }"
                />
              </div>
            </template>

            <!-- 下单时间 -->
            <template slot="createdAt" slot-scope="createdAt">
              <span class="text-sm text-slate-900">{{ createdAt }}</span>
            </template>

            <!-- 操作 -->
            <template slot="action" slot-scope="text, record">
              <div class="flex justify-end gap-2">
                <a-button
                  size="small"
                  class="h-7 px-3 text-blue-600 border-blue-300"
                  @click="handleViewDetail(record)"
                >
                  <a-icon type="file-text" />
                  查询
                </a-button>
                <a-button
                  size="small"
                  class="h-7 px-3 text-blue-600 border-blue-300"
                  @click="handleViewDetail(record)"
                >
                  <a-icon type="edit" />
                  详情
                </a-button>
              </div>
            </template>
          </a-table>
        </div>
      </a-card>
    </div>
  </sidebar>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, computed, onMounted } from '@vue/composition-api'
import Sidebar from '@/components/Layout/Sidebar.vue'
import OrderDetailDialog from './components/OrderDetailDialog.vue'
import OrderService from './services/order.service'
import type { Order, OrderFilterParams } from './types/order.types'
import { OrderStatus, ORDER_STATUS_LABELS, ORDER_STATUS_COLORS } from './types/order.types'
import dayjs, { Dayjs } from 'dayjs'

export default defineComponent({
  name: 'OrderListPage',
  components: {
    Sidebar,
    OrderDetailDialog
  },

  setup() {
    // ========== 状态管理 ==========
    const loading = ref(false)
    const orders = ref<Order[]>([])
    const total = ref(0)
    const currentPage = ref(1)
    const pageSize = ref(10)

    // 筛选条件
    const filters = reactive({
      roomType: '',
      startDate: undefined as Dayjs | undefined,
      endDate: undefined as Dayjs | undefined,
      orderStatus: 'all'
    })

    // 详情弹窗
    const isDetailDialogOpen = ref(false)
    const selectedOrder = ref<Order | null>(null)

    // ========== 表格配置 ==========
    const columns = [
      { title: '订单号', dataIndex: 'orderNumber', scopedSlots: { customRender: 'orderNumber' } },
      { title: '订房人', scopedSlots: { customRender: 'guestInfo' } },
      { title: '房型', dataIndex: 'roomType' },
      { title: '入住日期', scopedSlots: { customRender: 'checkInDates' } },
      { title: '支付金额', dataIndex: 'actualAmount', scopedSlots: { customRender: 'actualAmount' } },
      { title: '订单状态', dataIndex: 'status', scopedSlots: { customRender: 'status' } },
      { title: '下单时间', dataIndex: 'createdAt', scopedSlots: { customRender: 'createdAt' } },
      { title: '操作', align: 'right', scopedSlots: { customRender: 'action' }, width: 180 }
    ]

    // 分页配置
    const paginationConfig = computed(() => ({
      current: currentPage.value,
      pageSize: pageSize.value,
      total: total.value,
      showSizeChanger: true,
      showQuickJumper: true,
      showTotal: (total: number) => `共 ${total} 条`
    }))

    // ========== 数据加载 ==========
    const fetchOrders = async () => {
      loading.value = true
      try {
        const params: OrderFilterParams = {
          roomType: filters.roomType || undefined,
          startDate: filters.startDate ? dayjs(filters.startDate).format('YYYY-MM-DD') : undefined,
          endDate: filters.endDate ? dayjs(filters.endDate).format('YYYY-MM-DD') : undefined,
          orderStatus: filters.orderStatus === 'all' ? undefined : filters.orderStatus,
          page: currentPage.value,
          pageSize: pageSize.value
        }

        const response = await OrderService.getOrderList(params)
        orders.value = response.orders
        total.value = response.total
      } catch (error) {
        console.error('Failed to fetch orders:', error)
      } finally {
        loading.value = false
      }
    }

    // ========== 事件处理 ==========
    const handleSearch = () => {
      currentPage.value = 1
      fetchOrders()
    }

    const handleReset = () => {
      filters.roomType = ''
      filters.startDate = undefined
      filters.endDate = undefined
      filters.orderStatus = 'all'
      currentPage.value = 1
      fetchOrders()
    }

    const handleTableChange = (pagination: any) => {
      currentPage.value = pagination.current
      pageSize.value = pagination.pageSize
      fetchOrders()
    }

    const handleViewDetail = (order: Order) => {
      selectedOrder.value = order
      isDetailDialogOpen.value = true
    }

    // ========== 样式辅助 ==========
    const getStatusTagClass = (status: OrderStatus) => {
      const color = ORDER_STATUS_COLORS[status]
      const colorMap: Record<string, string> = {
        'orange': 'bg-orange-100 text-orange-700 border-orange-300',
        'blue': 'bg-blue-100 text-blue-700 border-blue-300',
        'black': 'bg-slate-100 text-slate-700 border-slate-300',
        'slate': 'bg-slate-100 text-slate-500 border-slate-300',
        'red': 'bg-red-100 text-red-700 border-red-300'
      }
      return colorMap[color] || 'bg-gray-100 text-gray-700 border-gray-300'
    }

    // ========== 生命周期 ==========
    onMounted(() => {
      fetchOrders()
    })

    return {
      // 状态
      loading,
      orders,
      filters,
      isDetailDialogOpen,
      selectedOrder,

      // 表格
      columns,
      paginationConfig,

      // 枚举
      OrderStatus,
      ORDER_STATUS_LABELS,

      // 方法
      handleSearch,
      handleReset,
      handleTableChange,
      handleViewDetail,
      getStatusTagClass
    }
  }
})
</script>

<style scoped lang="less">
.p-6 {
  padding: 24px;
}

.space-y-6 > * + * {
  margin-top: 24px;
}

.space-y-2 > * + * {
  margin-top: 8px;
}

.space-y-1 > * + * {
  margin-top: 4px;
}

.rounded-xl {
  border-radius: 12px;
}

.rounded-lg {
  border-radius: 8px;
}

.border-slate-200 {
  border-color: #e2e8f0;
}

.bg-white {
  background-color: #ffffff;
}

.shadow-sm {
  box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
}

.grid {
  display: grid;
}

.grid-cols-6 {
  grid-template-columns: repeat(6, minmax(0, 1fr));
}

.col-span-2 {
  grid-column: span 2 / span 2;
}

.col-span-3 {
  grid-column: span 3 / span 3;
}

.gap-2 {
  gap: 8px;
}

.gap-4 {
  gap: 16px;
}

.flex {
  display: flex;
}

.items-center {
  align-items: center;
}

.justify-end {
  justify-content: flex-end;
}

.h-7 {
  height: 28px;
}

.h-9 {
  height: 36px;
}

.px-3 {
  padding-left: 12px;
  padding-right: 12px;
}

.text-sm {
  font-size: 14px;
}

.text-lg {
  font-size: 18px;
}

.font-semibold {
  font-weight: 600;
}

.font-medium {
  font-weight: 500;
}

.font-mono {
  font-family: monospace;
}

.text-slate-600 {
  color: #475569;
}

.text-slate-900 {
  color: #0f172a;
}

.text-blue-600 {
  color: #2563eb;
}

.border-blue-300 {
  border-color: #93c5fd;
}

.border-slate-300 {
  border-color: #cbd5e1;
}

.bg-blue-600 {
  background-color: #2563eb;
}

.whitespace-nowrap {
  white-space: nowrap;
}

/* 状态标签样式 */
.bg-orange-100 {
  background-color: #ffedd5;
}
.text-orange-700 {
  color: #c2410c;
}
.border-orange-300 {
  border-color: #fdba74;
}

.bg-blue-100 {
  background-color: #dbeafe;
}
.text-blue-700 {
  color: #1d4ed8;
}

.bg-slate-100 {
  background-color: #f1f5f9;
}
.text-slate-700 {
  color: #334155;
}
.text-slate-500 {
  color: #64748b;
}

.bg-red-100 {
  background-color: #fee2e2;
}
.text-red-700 {
  color: #b91c1c;
}
.border-red-300 {
  border-color: #fca5a5;
}

.mt-4 {
  margin-top: 16px;
}

.w-full {
  width: 100%;
}

.flex-1 {
  flex: 1 1 0%;
}
</style>

// app/pages/HotelBackend/OrderList/OrderListPage.tsx
import { useState } from 'react'
import { Form, Link, useNavigate } from '@remix-run/react'
import type { OrderListResponse } from './types/orderList.types'
import { ORDER_STATUS_LABELS, ORDER_STATUS_COLORS } from './types/orderList.types'
import { OrderStatus } from '~/pages/SharedTypes/order.types'
import { Card, CardContent } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'
import { Search, Edit, FileText, ChevronLeft, ChevronRight } from 'lucide-react'
import { cn } from '~/lib/utils'
import MainLayout from '~/pages/PointsSystem/components/MainLayout'

interface OrderListPageProps {
  result: OrderListResponse | null
  error: string | null
}

export default function OrderListPage({ result, error }: OrderListPageProps) {
  const navigate = useNavigate()
  const [roomType, setRoomType] = useState('')
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')
  const [orderStatus, setOrderStatus] = useState('')

  const orders = result?.orders || []
  const currentPage = result?.page || 1
  const totalPages = result?.totalPages || 1
  const total = result?.total || 0

  const handlePageChange = (page: number) => {
    const params = new URLSearchParams(window.location.search)
    params.set('page', String(page))
    navigate(`?${params.toString()}`)
  }

  if (error) {
    return (
      <MainLayout>
        <div className="p-6">
          <div className="text-destructive">错误: {error}</div>
        </div>
      </MainLayout>
    )
  }

  return (
    <MainLayout>
      <div className="h-full overflow-y-auto">
        <div className="p-6 space-y-6">
      {/* 筛选表单 */}
      <Card>
        <CardContent className="pt-6">
          <Form method="get" className="space-y-4">
            <div className="grid grid-cols-6 gap-4">
              {/* 房型 */}
              <div className="space-y-2">
                <label className="text-sm text-muted-foreground">房型</label>
                <Input
                  name="roomType"
                  value={roomType}
                  onChange={(e) => setRoomType(e.target.value)}
                  placeholder="请选择房型"
                />
              </div>

              {/* 订房日期 */}
              <div className="space-y-2 col-span-2">
                <label className="text-sm text-muted-foreground">订房日期</label>
                <div className="flex gap-2 items-center">
                  <Input
                    type="date"
                    name="startDate"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    placeholder="开始日期"
                  />
                  <span>-</span>
                  <Input
                    type="date"
                    name="endDate"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    placeholder="结束日期"
                  />
                </div>
              </div>

              {/* 订单状态 */}
              <div className="space-y-2 col-span-3">
                <label className="text-sm text-muted-foreground">订单状态</label>
                <Select name="orderStatus" value={orderStatus} onValueChange={setOrderStatus}>
                  <SelectTrigger>
                    <SelectValue placeholder="全部状态" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">全部</SelectItem>
                    <SelectItem value={OrderStatus.PENDING_PAYMENT}>待支付</SelectItem>
                    <SelectItem value={OrderStatus.PENDING_CHECKIN}>待入住</SelectItem>
                    <SelectItem value={OrderStatus.CHECKED_IN}>入住中</SelectItem>
                    <SelectItem value={OrderStatus.CHECKED_OUT}>已离店</SelectItem>
                    <SelectItem value={OrderStatus.COMPLETED}>已完成</SelectItem>
                    <SelectItem value={OrderStatus.CANCELLED}>已取消</SelectItem>
                    <SelectItem value={OrderStatus.REFUND_REQUESTED}>退款申请</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="flex gap-2">
              <Button type="submit">
                <Search className="h-4 w-4 mr-2" />
                搜索
              </Button>
              <Button type="button" variant="outline" onClick={() => window.location.href = '/hotel-backend/order-list'}>
                重置
              </Button>
            </div>
          </Form>
        </CardContent>
      </Card>

      {/* 订单列表 */}
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>订单号</TableHead>
                <TableHead>订房人</TableHead>
                <TableHead>房型</TableHead>
                <TableHead>入住日期</TableHead>
                <TableHead>支付金额</TableHead>
                <TableHead>订单状态</TableHead>
                <TableHead>下单时间</TableHead>
                <TableHead className="text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {orders.map((order) => (
                <TableRow key={order.id}>
                  <TableCell className="font-mono text-sm">{order.orderNumber}</TableCell>
                  <TableCell>
                    <div className="space-y-1">
                      <div className="font-medium">{order.guestName}</div>
                      <div className="text-sm text-muted-foreground">{order.guestPhone}</div>
                    </div>
                  </TableCell>
                  <TableCell>{order.roomType}</TableCell>
                  <TableCell className="whitespace-nowrap">
                    {order.checkInDate} - {order.checkOutDate}
                  </TableCell>
                  <TableCell>¥{order.actualAmount}</TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <span
                        className={cn(
                          "px-2 py-1 rounded text-xs font-medium",
                          ORDER_STATUS_COLORS[order.status] === 'orange' && "bg-orange-100 text-orange-700",
                          ORDER_STATUS_COLORS[order.status] === 'blue' && "bg-blue-100 text-blue-700",
                          ORDER_STATUS_COLORS[order.status] === 'black' && "bg-slate-100 text-slate-700",
                          ORDER_STATUS_COLORS[order.status] === 'slate' && "bg-slate-100 text-slate-500",
                          ORDER_STATUS_COLORS[order.status] === 'red' && "bg-red-100 text-red-700"
                        )}
                      >
                        {ORDER_STATUS_LABELS[order.status]}
                      </span>
                      {order.hasRefundRequest && (
                        <span className="w-4 h-4 bg-red-500 rounded-full text-white text-[10px] flex items-center justify-center">
                          退
                        </span>
                      )}
                    </div>
                  </TableCell>
                  <TableCell className="text-sm">{order.createdAt}</TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      <Button variant="ghost" size="sm" className="text-blue-600 hover:text-blue-700">
                        <Edit className="h-4 w-4 mr-1" />
                        取消订单
                      </Button>
                      <Link to={`/hotel-backend/order-list/${order.id}`}>
                        <Button variant="ghost" size="sm" className="text-blue-600 hover:text-blue-700">
                          <FileText className="h-4 w-4 mr-1" />
                          查询
                        </Button>
                      </Link>
                      <Link to={`/hotel-backend/order-list/${order.id}/edit`}>
                        <Button variant="ghost" size="sm" className="text-blue-600 hover:text-blue-700">
                          <Edit className="h-4 w-4 mr-1" />
                          详情
                        </Button>
                      </Link>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          {orders.length === 0 && (
            <div className="text-center py-12 text-muted-foreground">
              暂无订单数据
            </div>
          )}

          {/* 分页 */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between px-6 py-4 border-t">
              <div className="text-sm text-muted-foreground">
                共 {total} 条，10条/页
              </div>
              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handlePageChange(currentPage - 1)}
                  disabled={currentPage === 1}
                >
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                {Array.from({ length: Math.min(5, totalPages) }, (_, i) => {
                  const page = i + 1
                  return (
                    <Button
                      key={page}
                      variant={page === currentPage ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => handlePageChange(page)}
                    >
                      {page}
                    </Button>
                  )
                })}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handlePageChange(currentPage + 1)}
                  disabled={currentPage === totalPages}
                >
                  <ChevronRight className="h-4 w-4" />
                </Button>
                <div className="flex items-center gap-2 ml-4">
                  <span className="text-sm text-muted-foreground">前往</span>
                  <Input
                    type="number"
                    min={1}
                    max={totalPages}
                    defaultValue={currentPage}
                    className="w-16 h-8 text-center"
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        const value = parseInt(e.currentTarget.value)
                        if (value >= 1 && value <= totalPages) {
                          handlePageChange(value)
                        }
                      }
                    }}
                  />
                  <span className="text-sm text-muted-foreground">页</span>
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
          </div>
        </div>
    </MainLayout>
  )
}
