// src/views/MerchantBackend/StoreInfo/components/EditableSection.vue
<template>
  <a-card
    :bordered="false"
    class="rounded-xl border-slate-200 bg-white shadow-md hover:shadow-lg transition-all duration-200"
  >
    <template #title>
      <div class="flex items-center justify-between">
        <span class="text-base font-semibold text-slate-900">{{ title }}</span>
        <div v-if="!hideActions" class="flex gap-2">
          <a-button
            v-if="!isEditing"
            type="primary"
            class="h-9 px-4 bg-blue-600 hover:bg-blue-700"
            @click="$emit('edit')"
          >
            编辑
          </a-button>
          <template v-else>
            <a-button
              class="h-9 px-4"
              :disabled="isSaving"
              @click="$emit('cancel')"
            >
              取消
            </a-button>
            <a-button
              type="primary"
              class="h-9 px-4 bg-blue-600 hover:bg-blue-700"
              :loading="isSaving"
              @click="$emit('save')"
            >
              {{ isSaving ? '保存中...' : '保存' }}
            </a-button>
          </template>
        </div>
      </div>
    </template>
    <slot />
  </a-card>
</template>

<script>
import { defineComponent } from '@vue/composition-api'

export default defineComponent({
  name: 'EditableSection',
  props: {
    title: {
      type: String,
      required: true
    },
    isEditing: {
      type: Boolean,
      default: false
    },
    isSaving: {
      type: Boolean,
      default: false
    },
    hideActions: {
      type: Boolean,
      default: false
    }
  }
})
</script>

// app/pages/MerchantBackend/StoreInfo/components/EditableSection.tsx
import { ReactNode } from 'react'
import { Button } from '~/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'

interface EditableSectionProps {
  title: string
  isEditing: boolean
  onEdit?: () => void
  onSave?: () => void
  onCancel?: () => void
  isSaving?: boolean
  children: ReactNode
  hideActions?: boolean
}

export default function EditableSection({
  title,
  isEditing,
  onEdit,
  onSave,
  onCancel,
  isSaving = false,
  children,
  hideActions = false,
}: EditableSectionProps) {
  return (
    <Card className="rounded-xl border-slate-200 bg-white shadow-md hover:shadow-lg transition-all duration-200">
      <CardHeader className="flex flex-row items-center justify-between border-b border-slate-100 pb-4">
        <CardTitle className="text-base font-semibold text-slate-900">{title}</CardTitle>
        {!hideActions && (
          <div className="flex gap-2">
            {!isEditing ? (
              <Button
                onClick={onEdit}
                className="h-9 px-4 bg-blue-600 hover:bg-blue-700 text-white font-medium shadow-sm transition-all"
              >
                编辑
              </Button>
            ) : (
              <>
                <Button
                  onClick={onCancel}
                  variant="outline"
                  className="h-9 px-4 border-slate-300 hover:border-slate-400 hover:bg-slate-50 font-medium transition-all"
                  disabled={isSaving}
                >
                  取消
                </Button>
                <Button
                  onClick={onSave}
                  className="h-9 px-4 bg-blue-600 hover:bg-blue-700 text-white font-medium shadow-sm transition-all"
                  disabled={isSaving}
                >
                  {isSaving ? '保存中...' : '保存'}
                </Button>
              </>
            )}
          </div>
        )}
      </CardHeader>
      <CardContent className="pt-6">{children}</CardContent>
    </Card>
  )
}
